apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
 name: postgres-ext-name
spec:
   type: ExternalName
   externalName: postgres.default.svc.cluster.local
