apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv2
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: "/postgres14/data/"