apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: superapp.com
      http:
        paths:
          - pathType: Prefix
            path: /v1
            backend:
              service:
                name: app-svc
                port: 
                  number: 80